In [1]:
import pandas as pd 

df = pd.read_csv('./dados/chess_games.csv')

df.head()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN

In [2]:
df["winner"]

0        White
1        Black
2        White
3        White
4        White
         ...
20053    White
20054    Black
20055    White
20056    White
20057    Black
Name: winner, Length: 20058, dtype: object

In [3]:
exemplo_dummy = pd.get_dummies(df["winner"])
exemplo_dummy

       Black   Draw  White
0      False  False   True
1       True  False  False
2      False  False   True
3      False  False   True
4      False  False   True
...      ...    ...    ...
20053  False  False   True
20054   True  False  False
20055  False  False   True
20056  False  False   True
20057   True  False  False

[20058 rows x 3 columns]

In [4]:
exemplo_dummy = pd.get_dummies(df["winner"]).astype(int)
exemplo_dummy

       Black  Draw  White
0          0     0      1
1          1     0      0
2          0     0      1
3          0     0      1
4          0     0      1
...      ...   ...    ...
20053      0     0      1
20054      1     0      0
20055      0     0      1
20056      0     0      1
20057      1     0      0

[20058 rows x 3 columns]

In [5]:
exemplo_tempo = pd.get_dummies(df["time_increment"])
exemplo_tempo

,0+12,0+13,0+15,0+16,0+180,0+20,0+25,0+30,0+40,1+10,...,9+5,9+6,9+7,9+8,9+9,90+0,90+120,90+30,90+5,90+8
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20054,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20055,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20056,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20057,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
exemplo_op_code = pd.get_dummies(df["opening_code"])
exemplo_op_code

,A00,A01,A02,A03,A04,A05,A06,A07,A08,A09,...,E81,E87,E88,E90,E91,E92,E94,E95,E97,E98
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20054,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20055,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20056,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20057,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
exemplo_op_moves = pd.get_dummies(df['opening_moves'])
exemplo_op_moves

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,22,24,28
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20054,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20055,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20056,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20057,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
exemplo_op_fullname = pd.get_dummies(df["opening_fullname"])
exemplo_op_fullname

,Alekhine Defense,Alekhine Defense #2,Alekhine Defense #3,Alekhine Defense: Balogh Variation,Alekhine Defense: Brooklyn Variation,Alekhine Defense: Exchange Variation,Alekhine Defense: Four Pawns Attack,Alekhine Defense: Four Pawns Attack | 6...Nc6,Alekhine Defense: Four Pawns Attack | Fianchetto Variation,Alekhine Defense: Four Pawns Attack | Main Line,...,Zukertort Opening: Quiet System,Zukertort Opening: Reversed Mexican Defense,Zukertort Opening: Ross Gambit,Zukertort Opening: Santasiere's Folly,Zukertort Opening: Sicilian Invitation,Zukertort Opening: Slav Invitation,Zukertort Opening: Tennison Gambit,Zukertort Opening: The Walrus,Zukertort Opening: Vos Gambit,Zukertort Opening: Wade Defense
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20054,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20055,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20056,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20057,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
exemplo_op_shortname = pd.get_dummies(df['opening_shortname'])
exemplo_op_shortname

,Alekhine Defense,Amar Opening,Amazon Attack,Anderssen Opening,Australian Defense,Barnes Defense,Barnes Opening,Benko Gambit,Benoni Defense,Bird Opening,...,Trompowsky Attack,Valencia Opening,Van Geet Opening,Van't Kruijs Opening,Vienna Game,Wade Defense,Ware Defense,Ware Opening,Yusupov-Rubinstein System,Zukertort Opening
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20054,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20055,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20056,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20057,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
exemplo_op_response = pd.get_dummies(df['opening_response'])
exemplo_op_response

       Accepted  Declined  Refused
0         False     False    False
1         False     False    False
2         False     False    False
3         False     False    False
4         False     False    False
...         ...       ...      ...
20053     False     False    False
20054     False     False    False
20055     False     False    False
20056     False     False    False
20057     False     False    False

[20058 rows x 3 columns]

In [11]:
exemplo_op_variation = pd.get_dummies(df['opening_variation'])
exemplo_op_variation

,#2,#3,#4,#5,2.b3,3.Nc3,4.Bg5 Be7,4.e3 e8g8,Accelerated Averbakh Variation,Accelerated Dragon,...,Zeller Defense,Zhuravlev Countergambit #2,Zilbermints Gambit,Zinnowitz Variation,Zukertort System,Zukertort Variation,Zurich Gambit,von Hennig Gambit,von Popiel Gambit,von der Lasa Gambit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20054,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20055,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20056,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20057,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False